apiVersion: v1
kind: Service
metadata:
  name: rental-service
  labels:
    app: rental-service
spec:
  type: ClusterIP
  selector:
    app: rental-service
  ports:
    - name: http
      port: 4000
      targetPort: 4000
